services:
  mysql:
    image: mysql:latest
    container_name: mysql-payment
    environment:
      MYSQL_DATABASE: micro_service_payment
      MYSQL_ROOT_PASSWORD: P@ssW0rd32!
    ports:
      - '3307:3306'
  redis:
    image: redis:latest
    container_name: redis-payment
    restart: always
    ports:
      - '6380:6379'